#!/bin/sh
dustc pubmed_article.dust ../../public/dust/pubmed_article_dust.js 
dustc wiki_article.dust ../../public/dust/wiki_article_dust.js 
dustc pubmed_list.dust ../../public/dust/pubmed_list_dust.js 
